### ISSUE TITLE
Exclude all child Notes from the full record page

### ISSUE THREAD

**Issue by drmikeuk** [whiskyechobravo/kerkoapp#13]
Hi,

I'm trying to exclude all child Notes from the full record page.
I added KERKOAPP_EXCLUDE_DEFAULT_FIELDS=notes to my .env but they still appear.

This, from the documentation, looks like what I'm after:
KERKOAPP_EXCLUDE_DEFAULT_FIELDS: List of fields (identified by key) to exclude from those created by default. If that list contains the value '*', no field will be created by default. Caution: some default fields are required by Kerko or by badges. If required fields are excluded, the application probably won't start. Please refer to the implementation of kerko.composer.Composer.init_default_fields() for the list of default fields.

composer.py contains the following so I used key='notes'.
Have I missed something?
Thanks,
mike

# Child notes of the item.
if 'notes' not in exclude:
    self.add_field(
        FieldSpec(
            key='notes',
            field_type=STORED,
            extractor=extractors.RawNotesExtractor(
                include_re=self.default_child_include_re,
                exclude_re=self.default_child_exclude_re
            )
        )
    )

**Comment by davidlesieur** [comment]
Hi, after adding `KERKOAPP_EXCLUDE_DEFAULT_FIELDS=notes` to your `.env` file, have you cleaned and re-synchronized your search index? The notes might still be in the search index because of a preview synchronization.

Also, you will probably to exclude the `text_notes` field as well (`KERKOAPP_EXCLUDE_DEFAULT_FIELDS=notes,text_notes`), otherwise the notes will be searchable.

I hope this helps!

**Comment by drmikeuk** [comment]
Thanks a lot, thats sorted it.
I missed the `flask kerko clean index` step.

**Comment by drmikeuk** [comment]
PS Great bit of software!

One other thing that confused me...

The Environment variables section says:
KERKO_ZOTERO_LIBRARY_ID: Your personal userID for API calls, as given on zotero.org (you must be logged-in on zotero.org).
KERKO_ZOTERO_LIBRARY_TYPE: The type of library on zotero.org (either 'user' for your main personal library, or 'group' for a group library).

and the Configuration example section shows:
KERKO_ZOTERO_LIBRARY_ID=**2348869**
KERKO_ZOTERO_LIBRARY_TYPE=group

which links to https://www.zotero.org/groups/**2348869**/kerko_demo/library

but i think **2348869** is the groupID not your personal userID for API calls?
I used my groupID and it works for me!

If it should be groupID when type=group maybe you could make this clearer in the documentation?

**Comment by davidlesieur** [comment]
Glad it worked! 

Regarding the incomplete documentation for the `KERKO_ZOTERO_LIBRARY_ID` variable, you are right. Thanks for pointing that out! To be fixed.
