### ISSUE TITLE
Changing "Kerko Demo" Text

### ISSUE THREAD

**Issue by richardkaplan** [whiskyechobravo/kerkoapp#2]
This looks like a wonderful contribution - huge thanks

Question - Is it possible to edit the "Kerko Demo" text in the top left?

**Comment by davidlesieur** [comment]
Have a look at [Kerko's variables](https://github.com/whiskyechobravo/kerko#configuration-variables). The one you'll want to set in your `.env` file is `KERKO_TITLE`.

**Comment by richardkaplan** [comment]
Thanks. 

Since it says the default is "Kerko" does that mean that the word "Demo" is hardcoded?

**Comment by davidlesieur** [comment]
If you see "Kerko Demo" when running the application, then it would (normally) imply that your `.env` file has the line `KERKO_TITLE=Kerko Demo`. You may edit the `.env` file.

**Comment by richardkaplan** [comment]
Thanks
