### ISSUE TITLE
Image added on custom content page based on Zotero standalone notes not showing in Kerkoapp

### ISSUE THREAD

**Issue by kmafoudji** [whiskyechobravo/kerkoapp#45]
Hello team, Have created a standalone notes with text and image from my Zotero web account. And linked it on my navbar. After syncing The page is showing on the navbar. But it doesn't content the image, just showing  the text.
Is there a way to display the image included in the note on the page?

Thank you for your help

**Comment by davidlesieur** [comment]
At the moment, there is unfortunately no way for Kerko to display image items embedded in notes.
