### ISSUE TITLE
502 Bad Gateway After adding custom template 

### ISSUE THREAD

**Issue by kmafoudji** [whiskyechobravo/kerkoapp#46]
Hello Team, I followed the answers provided on post [#40](https://github.com/whiskyechobravo/kerkoapp/issues/40) to make slight changes to the kerkoapp home page. For example, to change the color of the nav bar, I did this:
- created a "custom-theme" folder and added a layout.html.jinja2 file (content taken from the following layout file: [layout.html.jinja2](https://github.com/whiskyechobravo/kerko/blob/main/src/kerko/templates/kerko /layout.html.jinja2))
- modified line 37 of the layout file like this : <nav class="navbar navbar-expand-md **navbar-warning** **bg-warning** d-print-none">
- added the following lines in config.toml:
     [kerko.templates]
     layout = "custom-theme/layout.html.jinja2"
After restarting kerko I receive the error 502 Bad Gateway

What did I miss?
Thank you for your help

**Comment by kmafoudji** [comment]
Hello team, Any Help on this ?

**Comment by davidlesieur** [comment]
You didn't show how the template was modified. Have you tried running the app with the `flask --debug run` command? The console should then display error messages, and that should help you understand what's happening.

**Comment by kmafoudji** [comment]
Thank you for your answer. I'm giving more détails here :

- I changed **nav class="navbar navbar-expand-md navbar-dark bg-dark d-print-none"** by **nav class="navbar navbar-expand-md navbar-warning bg-warning d-print-none"** :

<img width="494" alt="image" src="https://github.com/whiskyechobravo/kerkoapp/assets/46994010/497f03e9-2bac-44bc-aae7-133e952924eb">

- The layout is placed in a folder "custom-theme" : 

<img width="256" alt="image" src="https://github.com/whiskyechobravo/kerkoapp/assets/46994010/91cec2f3-9fe9-460a-a75e-c6ec5abe7526">

- And called in my config file : 

[kerko.templates]
layout = "custom-theme/layout.html.jinja2"

After that i runned the following commands : 
flask --debug kerko clean everything
flask --debug kerko sync
At the first time i get this message : 
<img width="854" alt="image" src="https://github.com/whiskyechobravo/kerkoapp/assets/46994010/43c85566-f3e7-4d14-a5de-05d7711d2868">
I runned a second time the sync command, which executed correctly until the end.
I stopped and started the server. on my page I got this : 
<img width="430" alt="image" src="https://github.com/whiskyechobravo/kerkoapp/assets/46994010/871e7b1a-77a8-4e5b-8312-ac5c15f2d77e">

Results after running flask --debug run : 
<img width="460" alt="image" src="https://github.com/whiskyechobravo/kerkoapp/assets/46994010/2dace1d3-d9dd-4b61-8e14-ba7c84fc630a">

**Comment by kmafoudji** [comment]
Thank you for your answer. I'm giving more détails here :

- I changed **nav class="navbar navbar-expand-md navbar-dark bg-dark d-print-none"** by **nav class="navbar navbar-expand-md navbar-warning bg-warning d-print-none"** :

<img width="494" alt="image" src="https://github.com/whiskyechobravo/kerkoapp/assets/46994010/497f03e9-2bac-44bc-aae7-133e952924eb">

- The layout is placed in a folder "custom-theme" : 

<img width="256" alt="image" src="https://github.com/whiskyechobravo/kerkoapp/assets/46994010/91cec2f3-9fe9-460a-a75e-c6ec5abe7526">

- And called in my config file : 

[kerko.templates]
layout = "custom-theme/layout.html.jinja2"

After that i runned the following commands : 
flask --debug kerko clean everything
flask --debug kerko sync
At the first time i get this message : 
<img width="854" alt="image" src="https://github.com/whiskyechobravo/kerkoapp/assets/46994010/43c85566-f3e7-4d14-a5de-05d7711d2868">
I runned a second time the sync command, which executed correctly until the end.
I stopped and started the server. on my page I got this : 
<img width="430" alt="image" src="https://github.com/whiskyechobravo/kerkoapp/assets/46994010/871e7b1a-77a8-4e5b-8312-ac5c15f2d77e">

Results after running flask --debug run : 
<img width="460" alt="image" src="https://github.com/whiskyechobravo/kerkoapp/assets/46994010/2dace1d3-d9dd-4b61-8e14-ba7c84fc630a">

**Comment by kmafoudji** [comment]
It's working after i moved my template in the correct location : ~/kerkoapp/kerkoapp/templates/custom-them
Thank you will go on my customization.

**Comment by davidlesieur** [comment]
Glad that it works! Wishing you all the best with the project.
