### ISSUE TITLE
Problems synching all articles from a specific library (and only those articles)

### ISSUE THREAD

**Issue by rbawden** [whiskyechobravo/kerkoapp#48]
Hi there! I am just trying out kerkoapp and want to synch a personal library. It works almost as expected except that I am not getting all items from my library and I am getting some items from another (shared) library:

1. Some files from a group library that is shared with me appear in the app, although I specified that I wanted my personal user library
2. Not all files in the personal library appear in the app. This also means that some of my custom facet collections are not showing as no items are found for them (although some are found in my zotero library).
3. When I change the library to the group library instead of the personal one, I get exactly the same results, i.e. exactly the same results, with the collections of my personal library and no error message (the group library does not contain the same collections)

I made sure to run `flask kerko clean index` and `flask kerko sync index` before doing `flask --debug run` each time.

Is there something I'm missing here? Basically, I want all of the bibliographic items of the specified library to appear (and no other articles in other libraries).

Thank you in advance for your help!

**Comment by davidlesieur** [comment]
After changing your library ID in the config, make sure to run these commands:

```
flask kerko clean everything
flask kerko sync
```

Cleaning the index is not sufficient as it cleans just the search index and not the cache.

**Comment by rbawden** [comment]
Thank you for your quick response - that solves the problem and I can now see all the articles and custom facets!
