### ISSUE TITLE
kerkoapp 1.1.x incompatible with kerko 1.1.0?

### ISSUE THREAD

**Issue by dbs** [whiskyechobravo/kerkoapp#49]
kerkoapp 1.1.x's `requirements/run.in` requires `kerko==1.1.0`

kerkoapp 1.1.x's version of `kerkoapp/__init__.py` includes the following line:

`translation_directories = ";".join(kerko.TRANSLATION_DIRECTORIES + ["translations"])`

However, kerko 1.1.0's version of `kerko/__init__.py` includes the following line:

`TRANSLATION_DIRECTORY = str(pathlib.Path(__file__).parent / "translations")`

At run time, kerkoapp will complain that it can't find `kerko.TRANSLATION_DIRECTORIES` and asks if you meant `kerko.TRANSLATION_DIRECTORY`

After manually correcting this line of code, I'm running into further translation-related errors, so I think the kerkoapp 1.1.x branch might need more backporting for the changes that went into the kerko 1.1.0 release.

**Comment by davidlesieur** [comment]
Could it be that you have inadvertently installed the latest Kerko instead of 1.1.0? The latest version's `setup.cfg` indicates 1.1.0 (I should probably change that), so that may lead pip to think you have 1.1.0. 

Here's the 1.1.0 `kerko/__init__py`, using the `TRANSLATION_DIRECTORIES` variable: https://github.com/whiskyechobravo/kerko/blob/1.1.0/src/kerko/__init__.py

Here's the latest `kerko/__init__py`, using the new `TRANSLATION_DIRECTORY` variable: https://github.com/whiskyechobravo/kerko/blob/2fe2419/src/kerko/__init__.py

**Comment by dbs** [comment]
Oh that's certainly possible! Here's what's in `.venv/lib/python3.10/site-packages/Kerko-1.1.0.dist-info/METADATA`:

  Metadata-Version: 2.1
  Name: Kerko
  Version: 1.1.0
  Summary: A Flask blueprint that provides a faceted search interface for bibliographies based on Zotero.
  Home-page: https://whiskyechobravo.github.io/kerko/

All of which looks good, but then down below in the Changelog section we see:

  ## Unreleased changes
  
  Backwards incompatible changes:                                                                                                                                                                             
  - The Python variable `kerko.TRANSLATION_DIRECTORIES` is now 
  `kerko.TRANSLATION_DIRECTORY`, and a string instead of a list. If you have a
  custom application, you may need to adapt your Babel configuration.                                                                                                                                       
  
  Other changes:
  - Improve documentation.
  - Reduce XML sitemaps size.

  ## 1.1.0 (2023-12-23)                                                                                                                                                                                       

  Features: 

So yeah, the version of 1.1.0 that got installed is definitely beyond 1.1.0!

I'll try uninstalling it and reinstalling it.

**Comment by dbs** [comment]
Yep that was it. Thank you!

**Comment by dbs** [comment]
Yep, that  was it. Thank you!
