### ISSUE TITLE
Running KerkoApp on Windows

### ISSUE THREAD

**Issue by Trivy** [whiskyechobravo/kerkoapp#5]
Thank you for this contribution, it is very appreciated!

FYI, I am running KerkoApp locally on a Windows platform. I had a couple of issues, not directly related to KerkoApp. I write them down here, in case this experience can be useful to someone else:
1. Regarding requirements: eventually, I had to create the virtual environment from Conda and make minor changes to *run.txt* before running `pip install -r requirements/run.txt`.
2. I had to pass the command `set FLASK_APP=kerkoapp.py` to *cmd.exe* before running `flask kerko index`.

With these slight changes, my bibliography is now available at http://127.0.0.1:5000/ in my browser! Thanks!

**Comment by davidlesieur** [comment]
Great to hear that you had it working on Windows! Could you detail the changes you had to make to `run.txt`? Perhaps I could integrate these changes to the master version.

**Comment by Trivy** [comment]
Sure, however the changes seem very specific to my own configuration. Here are the two lines I have changed:
```
certifi>=2019.3.9         # via requests
```
and
```
wrapt>=1.11.1             # via kerko
```
(in both case, changing from ```==``` to ```>=```)

**Comment by davidlesieur** [comment]
Ah, yes, I have pinned precise versions in `run.txt` by using pip-tools. That's a way to ensure reproducible results, but that is a bit too strict when distributing software. I'll think about it. Suggestions are welcome.

**Comment by davidlesieur** [comment]
Perhaps the README should suggest installing from `run.in` instead of `run.txt`. I could set minimal requirements (with `>=`) in `run.in`. Then `run.txt` would serve only to those who wish to reproduce the last verified combination of packages.

**Comment by Trivy** [comment]
Quite frankly, I don't think any change in the README is required: the problem I faced had more to do with `pip` and my specific computer configuration than with KerkoApp. 

However, perhaps a FAQ section with the following piece of advice could be useful:

When running `flask kerko index` in the shell, if you get an error: 

> No such command "kerko"

you can try using: `export FLASK_APP=kerkoapp.py` (or `set FLASK_APP=kerkoapp.py` on Windows).

**Comment by davidlesieur** [comment]
Good idea, I should add that to the docs. I wonder why `FLASK_APP` was not picked up from the `.env` file in your case though. I expect the `.env` file to be read from the current directory when running flask (per [python-dotenv](https://github.com/theskumar/python-dotenv)).
