### ISSUE TITLE
docker pull does not work

### ISSUE THREAD

**Issue by richardkaplan** [whiskyechobravo/kerkoapp#8]
I got this working (huge thanks!) as a demo on my home computer and now plan to move it to a server.

For some reason a docker pull no longer works as it did previously, even when I am logged into docker.

I get one of these responses:

`Error response from daemon: manifest for whiskyechobravo/kerkoapp:0.3alpha1-18-gf8b5603 not found
`

`Error response from daemon: pull access denied for whiskeyechobravo/kerkoapp, repository does not exist or may require 'docker login'`

**Comment by davidlesieur** [comment]
Glad you were able to get it working! `whiskyechobravo/kerkoapp:0.3alpha1-18-gf8b5603` no longer exists. It was really a test and I did not think anyone was using it already. Sorry for that! You might want to try `whiskyechobravo/kerkoapp` to get the latest, or `whiskyechobravo/kerkoapp:0.3alpha1-14-g3ae9ca1` which is more recent (despite the version number).

**Comment by richardkaplan** [comment]
`docker pull whiskyechobravo/kerkoapp:0.3alpha1-14-g3ae9ca1` works

Many thanks
